### ISSUE TITLE
bustabit new update

### ISSUE THREAD

**Issue by nytheros** [MageNume/bustabit-bot#6]
forget it

**Comment by nytheros** [comment]
error

**Comment by KylianCadet** [comment]
The bustabit site has been modified and so the selenium script is currently not working.
I've made a newer working version of the script according to the new site.
I did not push it yet because I suspect the site to use randomly generated class names. (eg: "_1QUsIcc0SPjOxwvm2IHPh-").
I'll wait until tomorrow to see if my assumptions was true, and then push the newer script.

Thank you for noticing me.
